#:schema node_modules/wrangler/config-schema.json
name = "kiaiiretekonchikushow-worker"
main = "src/index.ts"
compatibility_date = "2024-09-25"

routes = [
  { pattern = "api.kiaiiretekonchiku.show", custom_domain = true }
]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[durable_objects.bindings]]
name = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[[migrations]]
tag = "v2"
new_classes = ["WebSocketHibernationServer"]
